esphome:
  name: sonoff_zigbee_bridge
  platform: ESP8266
  board: esp_wroom_02 # 2MB

wifi:
  ssid: YOUR_SSID
  password: YOUR_PASSWORD

  # Fixed MAC-based dhcp lease recommended, or static IP:
  # manual_ip:
  #   static_ip: 10.0.0.42
  #   gateway: 10.0.0.1
  #   subnet: 255.255.255.0

api:
  # set this if your bridge is not added to HA, to prevent periodic reboots:
  # reboot_timeout: 0s 

logger:
  baud_rate: 0 # disable serial logging; pins are used for zb module comm

ota:

uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 115200 # matched to fw: ncp-uart-sw_6.7.8_115200.ota

serial_server:
  port: 8888 # optional, default is 8888
  multi_client: false # optional, default is false. Set to true to allow multiple simultaneous connections

# optional binary sensor to monitor serial connection:
binary_sensor:
  - platform: serial_server
    name: Zigbee to serial
    on_press:
      - light.turn_on: green_led_light
    on_release:
      - light.turn_off: green_led_light

status_led:
  pin:
    number: GPIO13
    inverted: true

output:
  # the 3 lines below control the Green LED
  - platform: esp8266_pwm
    id: green_led
    pin: GPIO0
    inverted: True

light:
  # the 4 lines below define the Green LED light, to expose in HomeAssistant remove line "internal: true"
  - platform: monochromatic
    id: green_led_light
    output: green_led
    internal: true # hides the Green LED from Homeassistant
